name: Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 下载代码
      - name: deploy aliyun
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PSD }}
        run: |
          ls
          echo "开始啦啦"
          git pull
          node app.js
